### ISSUE TITLE
无法搜索樱花动漫

### ISSUE THREAD

**Issue by mokurin000** [zaxtyson/Anime-API#1]
502错误：yhdm.tv/search

**Comment by poly000** [comment]
樱花动漫是不是移动域名了

**Comment by zaxtyson** [comment]
樱花动漫有几个站的，目前这个资源多点，不过有时候502错误，等一等就好了哈哈
这个API还没更新，试一下这个 https://github.com/zaxtyson/AnimeSearcher/tree/dev

**Comment by poly000** [comment]
> 樱花动漫有几个站的，目前这个资源多点，不过有时候502错误，等一等就好了哈哈
> 这个API还没更新，试一下这个 https://github.com/zaxtyson/AnimeSearcher/tree/dev

最新测试板是不是这个分支的

**Comment by mokurin000** [comment]
> 樱花动漫有几个站的，目前这个资源多点，不过有时候502错误，等一等就好了哈哈
> 这个API还没更新，试一下这个 https://github.com/zaxtyson/AnimeSearcher/tree/dev

还是502（

**Comment by zaxtyson** [comment]
啊这，我这边正常欸

![image](https://user-images.githubusercontent.com/20383074/97067425-aa180500-15ef-11eb-89d3-210697b9e943.png)

**Comment by mokurin000** [comment]
> 啊这，我这边正常欸
> 
> ![image](https://user-images.githubusercontent.com/20383074/97067425-aa180500-15ef-11eb-89d3-210697b9e943.png)

我好像是联通网

**Comment by mokurin000** [comment]
我这边访问yhdm.tv直接跳转到yhdm.io了……

**Comment by zaxtyson** [comment]
我这边也是重定向了，可能他们又在改域名了
以前早上有时候网站会打不开，不知道最近如何
