### ISSUE TITLE
发生错误时的输出格式

### ISSUE THREAD

**Issue by StoneMoe** [zaxtyson/Anime-API#6]
当发生错误时，输出完整的json格式

而不是返回纯字符串，如`Parse anime detail info failed`，会更加程序友好

**Comment by zaxtyson** [comment]
给前端调用的接口都是 JSON 或者 Websocket, 这个信息是写在日志里面的.

因为现在时间比较紧张, 可能有些引擎很久没维护, 有些资源解析失败了, 见谅哈. 前端同学还在努力加功能, 我这都没时间折腾了, `dev` 分支很久之前提交的, 还有些功能没做呜, 还要维护那一堆引擎, 目前着实遭不住emm
